// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0J7KhEPDgnAZePEcQxGR9VTvQiUDnJ7c',
    appId: '1:565296493631:web:a95e37dede10aae39f348a',
    messagingSenderId: '565296493631',
    projectId: 'flutter-ecommerce-ui-1-150d7',
    authDomain: 'flutter-ecommerce-ui-1-150d7.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-ui-1-150d7.appspot.com',
    measurementId: 'G-T4F1K096P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_SQGjXjUdM99Hsad4vgUZzaiPLyGMVMY',
    appId: '1:565296493631:android:46cb724f173522c89f348a',
    messagingSenderId: '565296493631',
    projectId: 'flutter-ecommerce-ui-1-150d7',
    storageBucket: 'flutter-ecommerce-ui-1-150d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcAq1OoQfpQLw3-4sPdu1ZLcu_oER6eaU',
    appId: '1:565296493631:ios:8f9ec694bcf3826b9f348a',
    messagingSenderId: '565296493631',
    projectId: 'flutter-ecommerce-ui-1-150d7',
    storageBucket: 'flutter-ecommerce-ui-1-150d7.appspot.com',
    iosClientId: '565296493631-jrchn1ciq11dkav0i50sm1pv0es3d68c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcAq1OoQfpQLw3-4sPdu1ZLcu_oER6eaU',
    appId: '1:565296493631:ios:8f9ec694bcf3826b9f348a',
    messagingSenderId: '565296493631',
    projectId: 'flutter-ecommerce-ui-1-150d7',
    storageBucket: 'flutter-ecommerce-ui-1-150d7.appspot.com',
    iosClientId: '565296493631-jrchn1ciq11dkav0i50sm1pv0es3d68c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter1',
  );
}
